#ifndef INC_278292_SNAKE_SNAKEBOARD_H
#define INC_278292_SNAKE_SNAKEBOARD_H

enum GameMode  { DEBUG, EASY, NORMAL, HARD };
enum GameState { RUNNING, FINISHED_WIN, FINISHED_LOSS };
enum FieldState { EMPTY, SNAKE_HEAD, SNAKE_BODY, SNAKE_TAIL, APPLE, OBSTICLE};

class SnakeBoard {



};


#endif //INC_278292_SNAKE_SNAKEBOARD_H
